name: Build and Package JAR

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew clean build
        
      - uses: mr-smithers-excellent/docker-build-push@v6.7
        name: Build & push Docker image
        with:
          image: jk2pr/towntalk
          tags: v1
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
